image: docker:20
services:
  - docker:20-dind

stages:
  - build

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com

build:
  stage: build
  script:
    - docker build -t registry.gitlab.com/allanit/rendering-service .
    - docker push registry.gitlab.com/allanit/rendering-service
  only:
    - main
